### ISSUE TITLE
Get rid of unsafe by using byteorder

### ISSUE THREAD

**Issue by VictorKoenders** [RyanSquared/Syntixi-VM#3]
https://github.com/RyanSquared/Syntixi-VM/blob/2a9b24ad542741a67813d0f78ca94969cf4820b2/src/undump.rs#L123-L125

https://crates.io/crates/byteorder

**Comment by RyanSquared** [comment]
no, i'm keeping the transmute to keep it closer to how PUC-Rio Lua works
